apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-12T02:20:49Z"
  name: carts-canary
  resourceVersion: "1138993"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: 0369f0ba-1c86-11ea-b2d7-42010a9800a7
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
